apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Kroki
spec:
  description: Kroki provides a unified API with support for many diagram libraries including Mermaid, BPMN, and Excalidraw.
  tags:
    - Diagram
    - Tool
  readme: |
    # Kroki
    Kroki provides a unified API with support for many diagram libraries including Mermaid, BPMN, and Excalidraw.
  services:
    - name: Kroki
      template: PREBUILT_V2
      spec:
        source:
          image: yuzutech/kroki
        ports:
          - name: web
            containerPort: 8000
            protocol: TCP
        env:
          - key: KROKI_MERMAID_HOST
            value: mermaid
          - key: KROKI_BPMN_HOST
            value: bpmn
          - key: KROKI_EXCALIDRAW_HOST
            value: excalidraw
    - name: Mermaid
      template: PREBUILT_V2
      spec:
        source:
          image: yuzutech/kroki-mermaid
        ports:
          - name: web
            containerPort: 8002
            protocol: TCP
    - name: BPMN
      template: PREBUILT_V2
      spec:
        source:
          image: yuzutech/kroki-bpmn
        ports:
          - name: web
            containerPort: 8003
            protocol: TCP
    - name: Excalidraw
      template: PREBUILT_V2
      spec:
        source:
          image: yuzutech/kroki-excalidraw
        ports:
          - name: web
            containerPort: 8004
            protocol: TCP